# Generated by Django 4.2.4 on 2023-08-07 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Translation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_language', models.CharField(choices=[('en', 'English')], max_length=2)),
                ('destination_language', models.CharField(choices=[('es', 'Spanish')], max_length=2)),
                ('content_type', models.CharField(choices=[('text', 'Text'), ('youtube', 'YouTube URL'), ('file', 'File')], max_length=10)),
                ('content', models.TextField()),
                ('translated_content', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
