# Generated by Django 4.2.4 on 2023-08-08 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translator_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='translation',
            name='input_file',
            field=models.FileField(default='input_file.txt', upload_to='input_files/'),
        ),
        migrations.AddField(
            model_name='translation',
            name='translated_file',
            field=models.FileField(blank=True, null=True, upload_to='translated_files/'),
        ),
    ]
