# Generated by Django 4.2.4 on 2023-08-08 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translator_app', '0002_translation_input_file_translation_translated_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='translation',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
