# Generated by Django 4.2.4 on 2023-08-08 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translator_app', '0003_alter_translation_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='translation',
            name='destination_language',
            field=models.CharField(choices=[('ta', 'Tamil'), ('ka', 'Kannada')], max_length=2),
        ),
        migrations.AlterField(
            model_name='translation',
            name='source_language',
            field=models.CharField(choices=[('ta', 'Tamil'), ('ka', 'Kannada')], max_length=2),
        ),
    ]
