# Generated by Django 4.2.4 on 2023-08-08 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translator_app', '0004_alter_translation_destination_language_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='translation',
            name='source_language',
            field=models.CharField(choices=[('en', 'English')], max_length=2),
        ),
    ]
