# Generated by Django 4.2.4 on 2023-08-08 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translator_app', '0005_alter_translation_source_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='translation',
            name='destination_language',
            field=models.CharField(choices=[('ta', 'Tamil'), ('kn', 'Kannada')], max_length=2),
        ),
    ]
