# Generated by Django 4.2.4 on 2023-08-08 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translator_app', '0006_alter_translation_destination_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='translation',
            name='pipeline_choice',
            field=models.CharField(choices=[('slm', 'SLM'), ('translate_folder', 'Translate Folder Highlighted Keywords')], default='slm', max_length=20),
        ),
    ]
