# Generated by Django 4.2.4 on 2023-09-07 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translator_app', '0007_translation_pipeline_choice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='translation',
            name='content',
        ),
        migrations.RemoveField(
            model_name='translation',
            name='translated_content',
        ),
        migrations.AlterField(
            model_name='translation',
            name='content_type',
            field=models.CharField(choices=[('file', 'File')], max_length=10),
        ),
        migrations.AlterField(
            model_name='translation',
            name='input_file',
            field=models.FileField(null=True, upload_to='input_files/'),
        ),
        migrations.AlterField(
            model_name='translation',
            name='pipeline_choice',
            field=models.CharField(choices=[('slm', 'SLM'), ('translate_file', 'Translate File Highlighted Keywords')], default='slm', max_length=20),
        ),
    ]
